[package]
name = "modem"
version = "0.0.1"
authors = ["Mick Koch <mick@kochm.co>"]

[dependencies]
getopts = "*"
num = "*"

[lib]
name = "modem"
path = "src/modem/lib.rs"

[[bin]]
name = "modulate"
path = "src/bin/modulate.rs"

[[bin]]
name = "fm"
path = "src/bin/fm.rs"
